# Generated by Django 5.2.7 on 2025-10-13 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('codigo_licitacao', models.CharField(db_index=True, max_length=100, unique=True)),
                ('orgao', models.CharField(max_length=300)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=255)),
                ('data_abertura', models.DateTimeField(db_index=True)),
                ('modalidade', models.CharField(max_length=100)),
                ('objeto', models.TextField()),
                ('link_edital', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(default='Abertta', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_alerta', models.CharField(max_length=100)),
                ('palavras_chave', models.CharField(blank=True, max_length=500, null=True)),
                ('estados', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidades', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
