# Generated by Django 5.2.7 on 2025-10-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacao',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='codigo_licitacao',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='link_edital',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='modalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='orgao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='status',
            field=models.CharField(default='Aberta', max_length=50),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Alerta',
        ),
    ]
